## To see all available configs, please check the documentation
## https://github.com/TerraHubCorp/terrahub/tree/master/docs
## project config
project:
  name: 'spoonsphere/hashicat-aws'
  code: '273ea3b8'
  include:
    - '.'
  exclude:
    - '**/.terraform/**'
    - '**/node_modules/**'
    - '**/.git/**'

## terraform config
terraform:
  varFile:
    - 'default.tfvars'
